version: "2"

services:
  application:
    image: debian
    volumes:
      - ./:/var/www/app
  workspace:
    image: dung13890/php-env:php7.3
    restart: always
    volumes_from:
      - application
    tty: true
